// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonProtoc.proto

package com.kindroid.kincent.protoc;

public final class CommonProtoc {
  private CommonProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum FeedbackType
      implements com.google.protobuf.ProtocolMessageEnum {
    GENERAL(0, 1),
    SEND_RECV_MSG(1, 2),
    COLLECT_MSG(2, 3),
    INTERCEPT_ANNOY(3, 4),
    PROTECT_PRIVACY(4, 5),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static FeedbackType valueOf(int value) {
      switch (value) {
        case 1: return GENERAL;
        case 2: return SEND_RECV_MSG;
        case 3: return COLLECT_MSG;
        case 4: return INTERCEPT_ANNOY;
        case 5: return PROTECT_PRIVACY;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<FeedbackType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FeedbackType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FeedbackType>() {
            public FeedbackType findValueByNumber(int number) {
              return FeedbackType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kindroid.kincent.protoc.CommonProtoc.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final FeedbackType[] VALUES = {
      GENERAL, SEND_RECV_MSG, COLLECT_MSG, INTERCEPT_ANNOY, PROTECT_PRIVACY, 
    };
    public static FeedbackType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private FeedbackType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.kindroid.kincent.protoc.CommonProtoc.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:com.kindroid.kincent.protoc.FeedbackType)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CommonProtoc.proto\022\033com.kindroid.kince" +
      "nt.protoc*i\n\014FeedbackType\022\013\n\007GENERAL\020\001\022\021" +
      "\n\rSEND_RECV_MSG\020\002\022\017\n\013COLLECT_MSG\020\003\022\023\n\017IN" +
      "TERCEPT_ANNOY\020\004\022\023\n\017PROTECT_PRIVACY\020\005B\035\n\033" +
      "com.kindroid.kincent.protoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
