// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedbackProtoc.proto

package com.kindroid.kincent.protoc;

public final class FeedbackProtoc {
  private FeedbackProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Feedback extends
      com.google.protobuf.GeneratedMessage {
    // Use Feedback.newBuilder() to construct.
    private Feedback() {
      initFields();
    }
    private Feedback(boolean noInit) {}
    
    private static final Feedback defaultInstance;
    public static Feedback getDefaultInstance() {
      return defaultInstance;
    }
    
    public Feedback getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.kincent.protoc.FeedbackProtoc.internal_static_com_kindroid_kincent_protoc_Feedback_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.kincent.protoc.FeedbackProtoc.internal_static_com_kindroid_kincent_protoc_Feedback_fieldAccessorTable;
    }
    
    // required .com.kindroid.kincent.protoc.FeedbackType feedbackType = 1;
    public static final int FEEDBACKTYPE_FIELD_NUMBER = 1;
    private boolean hasFeedbackType;
    private com.kindroid.kincent.protoc.CommonProtoc.FeedbackType feedbackType_;
    public boolean hasFeedbackType() { return hasFeedbackType; }
    public com.kindroid.kincent.protoc.CommonProtoc.FeedbackType getFeedbackType() { return feedbackType_; }
    
    // optional string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    // required string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private boolean hasContent;
    private java.lang.String content_ = "";
    public boolean hasContent() { return hasContent; }
    public java.lang.String getContent() { return content_; }
    
    // optional string manuer = 4;
    public static final int MANUER_FIELD_NUMBER = 4;
    private boolean hasManuer;
    private java.lang.String manuer_ = "";
    public boolean hasManuer() { return hasManuer; }
    public java.lang.String getManuer() { return manuer_; }
    
    // optional string model = 5;
    public static final int MODEL_FIELD_NUMBER = 5;
    private boolean hasModel;
    private java.lang.String model_ = "";
    public boolean hasModel() { return hasModel; }
    public java.lang.String getModel() { return model_; }
    
    // optional string fingerprint = 6;
    public static final int FINGERPRINT_FIELD_NUMBER = 6;
    private boolean hasFingerprint;
    private java.lang.String fingerprint_ = "";
    public boolean hasFingerprint() { return hasFingerprint; }
    public java.lang.String getFingerprint() { return fingerprint_; }
    
    // optional string imei = 7;
    public static final int IMEI_FIELD_NUMBER = 7;
    private boolean hasImei;
    private java.lang.String imei_ = "";
    public boolean hasImei() { return hasImei; }
    public java.lang.String getImei() { return imei_; }
    
    // optional string brand = 8;
    public static final int BRAND_FIELD_NUMBER = 8;
    private boolean hasBrand;
    private java.lang.String brand_ = "";
    public boolean hasBrand() { return hasBrand; }
    public java.lang.String getBrand() { return brand_; }
    
    // optional string board = 9;
    public static final int BOARD_FIELD_NUMBER = 9;
    private boolean hasBoard;
    private java.lang.String board_ = "";
    public boolean hasBoard() { return hasBoard; }
    public java.lang.String getBoard() { return board_; }
    
    // optional string osversion = 10;
    public static final int OSVERSION_FIELD_NUMBER = 10;
    private boolean hasOsversion;
    private java.lang.String osversion_ = "";
    public boolean hasOsversion() { return hasOsversion; }
    public java.lang.String getOsversion() { return osversion_; }
    
    // optional string sdkversion = 11;
    public static final int SDKVERSION_FIELD_NUMBER = 11;
    private boolean hasSdkversion;
    private java.lang.String sdkversion_ = "";
    public boolean hasSdkversion() { return hasSdkversion; }
    public java.lang.String getSdkversion() { return sdkversion_; }
    
    // optional string version = 12;
    public static final int VERSION_FIELD_NUMBER = 12;
    private boolean hasVersion;
    private java.lang.String version_ = "";
    public boolean hasVersion() { return hasVersion; }
    public java.lang.String getVersion() { return version_; }
    
    private void initFields() {
      feedbackType_ = com.kindroid.kincent.protoc.CommonProtoc.FeedbackType.GENERAL;
    }
    public final boolean isInitialized() {
      if (!hasFeedbackType) return false;
      if (!hasContent) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFeedbackType()) {
        output.writeEnum(1, getFeedbackType().getNumber());
      }
      if (hasEmail()) {
        output.writeString(2, getEmail());
      }
      if (hasContent()) {
        output.writeString(3, getContent());
      }
      if (hasManuer()) {
        output.writeString(4, getManuer());
      }
      if (hasModel()) {
        output.writeString(5, getModel());
      }
      if (hasFingerprint()) {
        output.writeString(6, getFingerprint());
      }
      if (hasImei()) {
        output.writeString(7, getImei());
      }
      if (hasBrand()) {
        output.writeString(8, getBrand());
      }
      if (hasBoard()) {
        output.writeString(9, getBoard());
      }
      if (hasOsversion()) {
        output.writeString(10, getOsversion());
      }
      if (hasSdkversion()) {
        output.writeString(11, getSdkversion());
      }
      if (hasVersion()) {
        output.writeString(12, getVersion());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFeedbackType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getFeedbackType().getNumber());
      }
      if (hasEmail()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmail());
      }
      if (hasContent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getContent());
      }
      if (hasManuer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getManuer());
      }
      if (hasModel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getModel());
      }
      if (hasFingerprint()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getFingerprint());
      }
      if (hasImei()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getImei());
      }
      if (hasBrand()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getBrand());
      }
      if (hasBoard()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getBoard());
      }
      if (hasOsversion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getOsversion());
      }
      if (hasSdkversion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getSdkversion());
      }
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getVersion());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.kincent.protoc.FeedbackProtoc.Feedback prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.kincent.protoc.FeedbackProtoc.Feedback result;
      
      // Construct using com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.kincent.protoc.FeedbackProtoc.Feedback();
        return builder;
      }
      
      protected com.kindroid.kincent.protoc.FeedbackProtoc.Feedback internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.kincent.protoc.FeedbackProtoc.Feedback();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.getDescriptor();
      }
      
      public com.kindroid.kincent.protoc.FeedbackProtoc.Feedback getDefaultInstanceForType() {
        return com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.kincent.protoc.FeedbackProtoc.Feedback build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.kincent.protoc.FeedbackProtoc.Feedback buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.kincent.protoc.FeedbackProtoc.Feedback buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.kincent.protoc.FeedbackProtoc.Feedback returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.kincent.protoc.FeedbackProtoc.Feedback) {
          return mergeFrom((com.kindroid.kincent.protoc.FeedbackProtoc.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.kincent.protoc.FeedbackProtoc.Feedback other) {
        if (other == com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.getDefaultInstance()) return this;
        if (other.hasFeedbackType()) {
          setFeedbackType(other.getFeedbackType());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasManuer()) {
          setManuer(other.getManuer());
        }
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasFingerprint()) {
          setFingerprint(other.getFingerprint());
        }
        if (other.hasImei()) {
          setImei(other.getImei());
        }
        if (other.hasBrand()) {
          setBrand(other.getBrand());
        }
        if (other.hasBoard()) {
          setBoard(other.getBoard());
        }
        if (other.hasOsversion()) {
          setOsversion(other.getOsversion());
        }
        if (other.hasSdkversion()) {
          setSdkversion(other.getSdkversion());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.kindroid.kincent.protoc.CommonProtoc.FeedbackType value = com.kindroid.kincent.protoc.CommonProtoc.FeedbackType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setFeedbackType(value);
              }
              break;
            }
            case 18: {
              setEmail(input.readString());
              break;
            }
            case 26: {
              setContent(input.readString());
              break;
            }
            case 34: {
              setManuer(input.readString());
              break;
            }
            case 42: {
              setModel(input.readString());
              break;
            }
            case 50: {
              setFingerprint(input.readString());
              break;
            }
            case 58: {
              setImei(input.readString());
              break;
            }
            case 66: {
              setBrand(input.readString());
              break;
            }
            case 74: {
              setBoard(input.readString());
              break;
            }
            case 82: {
              setOsversion(input.readString());
              break;
            }
            case 90: {
              setSdkversion(input.readString());
              break;
            }
            case 98: {
              setVersion(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .com.kindroid.kincent.protoc.FeedbackType feedbackType = 1;
      public boolean hasFeedbackType() {
        return result.hasFeedbackType();
      }
      public com.kindroid.kincent.protoc.CommonProtoc.FeedbackType getFeedbackType() {
        return result.getFeedbackType();
      }
      public Builder setFeedbackType(com.kindroid.kincent.protoc.CommonProtoc.FeedbackType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFeedbackType = true;
        result.feedbackType_ = value;
        return this;
      }
      public Builder clearFeedbackType() {
        result.hasFeedbackType = false;
        result.feedbackType_ = com.kindroid.kincent.protoc.CommonProtoc.FeedbackType.GENERAL;
        return this;
      }
      
      // optional string email = 2;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = getDefaultInstance().getEmail();
        return this;
      }
      
      // required string content = 3;
      public boolean hasContent() {
        return result.hasContent();
      }
      public java.lang.String getContent() {
        return result.getContent();
      }
      public Builder setContent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContent = true;
        result.content_ = value;
        return this;
      }
      public Builder clearContent() {
        result.hasContent = false;
        result.content_ = getDefaultInstance().getContent();
        return this;
      }
      
      // optional string manuer = 4;
      public boolean hasManuer() {
        return result.hasManuer();
      }
      public java.lang.String getManuer() {
        return result.getManuer();
      }
      public Builder setManuer(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasManuer = true;
        result.manuer_ = value;
        return this;
      }
      public Builder clearManuer() {
        result.hasManuer = false;
        result.manuer_ = getDefaultInstance().getManuer();
        return this;
      }
      
      // optional string model = 5;
      public boolean hasModel() {
        return result.hasModel();
      }
      public java.lang.String getModel() {
        return result.getModel();
      }
      public Builder setModel(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasModel = true;
        result.model_ = value;
        return this;
      }
      public Builder clearModel() {
        result.hasModel = false;
        result.model_ = getDefaultInstance().getModel();
        return this;
      }
      
      // optional string fingerprint = 6;
      public boolean hasFingerprint() {
        return result.hasFingerprint();
      }
      public java.lang.String getFingerprint() {
        return result.getFingerprint();
      }
      public Builder setFingerprint(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFingerprint = true;
        result.fingerprint_ = value;
        return this;
      }
      public Builder clearFingerprint() {
        result.hasFingerprint = false;
        result.fingerprint_ = getDefaultInstance().getFingerprint();
        return this;
      }
      
      // optional string imei = 7;
      public boolean hasImei() {
        return result.hasImei();
      }
      public java.lang.String getImei() {
        return result.getImei();
      }
      public Builder setImei(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasImei = true;
        result.imei_ = value;
        return this;
      }
      public Builder clearImei() {
        result.hasImei = false;
        result.imei_ = getDefaultInstance().getImei();
        return this;
      }
      
      // optional string brand = 8;
      public boolean hasBrand() {
        return result.hasBrand();
      }
      public java.lang.String getBrand() {
        return result.getBrand();
      }
      public Builder setBrand(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBrand = true;
        result.brand_ = value;
        return this;
      }
      public Builder clearBrand() {
        result.hasBrand = false;
        result.brand_ = getDefaultInstance().getBrand();
        return this;
      }
      
      // optional string board = 9;
      public boolean hasBoard() {
        return result.hasBoard();
      }
      public java.lang.String getBoard() {
        return result.getBoard();
      }
      public Builder setBoard(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBoard = true;
        result.board_ = value;
        return this;
      }
      public Builder clearBoard() {
        result.hasBoard = false;
        result.board_ = getDefaultInstance().getBoard();
        return this;
      }
      
      // optional string osversion = 10;
      public boolean hasOsversion() {
        return result.hasOsversion();
      }
      public java.lang.String getOsversion() {
        return result.getOsversion();
      }
      public Builder setOsversion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOsversion = true;
        result.osversion_ = value;
        return this;
      }
      public Builder clearOsversion() {
        result.hasOsversion = false;
        result.osversion_ = getDefaultInstance().getOsversion();
        return this;
      }
      
      // optional string sdkversion = 11;
      public boolean hasSdkversion() {
        return result.hasSdkversion();
      }
      public java.lang.String getSdkversion() {
        return result.getSdkversion();
      }
      public Builder setSdkversion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSdkversion = true;
        result.sdkversion_ = value;
        return this;
      }
      public Builder clearSdkversion() {
        result.hasSdkversion = false;
        result.sdkversion_ = getDefaultInstance().getSdkversion();
        return this;
      }
      
      // optional string version = 12;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public java.lang.String getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = getDefaultInstance().getVersion();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.kincent.protoc.Feedback)
    }
    
    static {
      defaultInstance = new Feedback(true);
      com.kindroid.kincent.protoc.FeedbackProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.kincent.protoc.Feedback)
  }
  
  public static final class FeedbackRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use FeedbackRequest.newBuilder() to construct.
    private FeedbackRequest() {
      initFields();
    }
    private FeedbackRequest(boolean noInit) {}
    
    private static final FeedbackRequest defaultInstance;
    public static FeedbackRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public FeedbackRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.kincent.protoc.FeedbackProtoc.internal_static_com_kindroid_kincent_protoc_FeedbackRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.kincent.protoc.FeedbackProtoc.internal_static_com_kindroid_kincent_protoc_FeedbackRequest_fieldAccessorTable;
    }
    
    // optional .com.kindroid.kincent.protoc.Feedback feedback = 1;
    public static final int FEEDBACK_FIELD_NUMBER = 1;
    private boolean hasFeedback;
    private com.kindroid.kincent.protoc.FeedbackProtoc.Feedback feedback_;
    public boolean hasFeedback() { return hasFeedback; }
    public com.kindroid.kincent.protoc.FeedbackProtoc.Feedback getFeedback() { return feedback_; }
    
    private void initFields() {
      feedback_ = com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasFeedback()) {
        if (!getFeedback().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFeedback()) {
        output.writeMessage(1, getFeedback());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFeedback()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFeedback());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest result;
      
      // Construct using com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest();
        return builder;
      }
      
      protected com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest.getDescriptor();
      }
      
      public com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest getDefaultInstanceForType() {
        return com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest) {
          return mergeFrom((com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest other) {
        if (other == com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest.getDefaultInstance()) return this;
        if (other.hasFeedback()) {
          mergeFeedback(other.getFeedback());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.Builder subBuilder = com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.newBuilder();
              if (hasFeedback()) {
                subBuilder.mergeFrom(getFeedback());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFeedback(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.kindroid.kincent.protoc.Feedback feedback = 1;
      public boolean hasFeedback() {
        return result.hasFeedback();
      }
      public com.kindroid.kincent.protoc.FeedbackProtoc.Feedback getFeedback() {
        return result.getFeedback();
      }
      public Builder setFeedback(com.kindroid.kincent.protoc.FeedbackProtoc.Feedback value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFeedback = true;
        result.feedback_ = value;
        return this;
      }
      public Builder setFeedback(com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.Builder builderForValue) {
        result.hasFeedback = true;
        result.feedback_ = builderForValue.build();
        return this;
      }
      public Builder mergeFeedback(com.kindroid.kincent.protoc.FeedbackProtoc.Feedback value) {
        if (result.hasFeedback() &&
            result.feedback_ != com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.getDefaultInstance()) {
          result.feedback_ =
            com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.newBuilder(result.feedback_).mergeFrom(value).buildPartial();
        } else {
          result.feedback_ = value;
        }
        result.hasFeedback = true;
        return this;
      }
      public Builder clearFeedback() {
        result.hasFeedback = false;
        result.feedback_ = com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.kincent.protoc.FeedbackRequest)
    }
    
    static {
      defaultInstance = new FeedbackRequest(true);
      com.kindroid.kincent.protoc.FeedbackProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.kincent.protoc.FeedbackRequest)
  }
  
  public static final class FeedbackResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use FeedbackResponse.newBuilder() to construct.
    private FeedbackResponse() {
      initFields();
    }
    private FeedbackResponse(boolean noInit) {}
    
    private static final FeedbackResponse defaultInstance;
    public static FeedbackResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public FeedbackResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.kincent.protoc.FeedbackProtoc.internal_static_com_kindroid_kincent_protoc_FeedbackResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.kincent.protoc.FeedbackProtoc.internal_static_com_kindroid_kincent_protoc_FeedbackResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse result;
      
      // Construct using com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse();
        return builder;
      }
      
      protected com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse.getDescriptor();
      }
      
      public com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse getDefaultInstanceForType() {
        return com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse) {
          return mergeFrom((com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse other) {
        if (other == com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.kincent.protoc.FeedbackResponse)
    }
    
    static {
      defaultInstance = new FeedbackResponse(true);
      com.kindroid.kincent.protoc.FeedbackProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.kincent.protoc.FeedbackResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_kincent_protoc_Feedback_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_kincent_protoc_Feedback_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_kincent_protoc_FeedbackRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_kincent_protoc_FeedbackRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_kincent_protoc_FeedbackResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_kincent_protoc_FeedbackResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024FeedbackProtoc.proto\022\033com.kindroid.kin" +
      "cent.protoc\032\022CommonProtoc.proto\"\203\002\n\010Feed" +
      "back\022?\n\014feedbackType\030\001 \002(\0162).com.kindroi" +
      "d.kincent.protoc.FeedbackType\022\r\n\005email\030\002" +
      " \001(\t\022\017\n\007content\030\003 \002(\t\022\016\n\006manuer\030\004 \001(\t\022\r\n" +
      "\005model\030\005 \001(\t\022\023\n\013fingerprint\030\006 \001(\t\022\014\n\004ime" +
      "i\030\007 \001(\t\022\r\n\005brand\030\010 \001(\t\022\r\n\005board\030\t \001(\t\022\021\n" +
      "\tosversion\030\n \001(\t\022\022\n\nsdkversion\030\013 \001(\t\022\017\n\007" +
      "version\030\014 \001(\t\"J\n\017FeedbackRequest\0227\n\010feed" +
      "back\030\001 \001(\0132%.com.kindroid.kincent.protoc",
      ".Feedback\"\022\n\020FeedbackResponseB\035\n\033com.kin" +
      "droid.kincent.protoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_kindroid_kincent_protoc_Feedback_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_kindroid_kincent_protoc_Feedback_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_kincent_protoc_Feedback_descriptor,
              new java.lang.String[] { "FeedbackType", "Email", "Content", "Manuer", "Model", "Fingerprint", "Imei", "Brand", "Board", "Osversion", "Sdkversion", "Version", },
              com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.class,
              com.kindroid.kincent.protoc.FeedbackProtoc.Feedback.Builder.class);
          internal_static_com_kindroid_kincent_protoc_FeedbackRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_kindroid_kincent_protoc_FeedbackRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_kincent_protoc_FeedbackRequest_descriptor,
              new java.lang.String[] { "Feedback", },
              com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest.class,
              com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackRequest.Builder.class);
          internal_static_com_kindroid_kincent_protoc_FeedbackResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_kindroid_kincent_protoc_FeedbackResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_kincent_protoc_FeedbackResponse_descriptor,
              new java.lang.String[] { },
              com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse.class,
              com.kindroid.kincent.protoc.FeedbackProtoc.FeedbackResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kindroid.kincent.protoc.CommonProtoc.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
